name: Adicionar cabeçalho de licença

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  license:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v3

      - name: Instalar Go (requisito do Skywalking Eyes)
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Instalar Skywalking Eyes (license-eye)
        run: |
          curl -sSfL https://raw.githubusercontent.com/apache/skywalking-eyes/main/scripts/install.sh | bash
          echo "$HOME/.skywalking-eyes/bin" >> $GITHUB_PATH
          export PATH="$HOME/.skywalking-eyes/bin:$PATH"

      - name: Injetar conteúdo do LICENSE no .licenserc.yaml
        run: |
          LICENSE_CONTENT=$(awk '{print_
